spring:
  application:
    name: competition-service  # Recommended to use lowercase
  datasource:
    url: jdbc:mysql://localhost:3306/competition?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ousama.sfaxi@gmail.com
    password: l x n g a x x c v v m u n p x z
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8075

welcome:
  message: Welcome to Competition Service

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate: INFO
    org.springframework.jdbc: DEBUG
    org.springframework.web: DEBUG
    tn.esprit: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

twilio:
  account:
    sid: AC293b569685f676bb0b61a7f5cdb84248
  auth:
    token: e3bd4556a730cf859ea158426e27d41b
  phone:
    number: "+18455761651"