# ========================
# APPLICATION CONFIGURATION
# ========================
server:
  port: 8070
  servlet:
    context-path: /

welcome:
  message: Welcome to equipe

# ====================
# DATABASE CONFIGURATION
# ====================
spring:
  datasource:
    username: root
    password: ""
    url: jdbc:mysql://localhost:3306/equipe?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ====================
  # HIBERNATE CONFIGURATION
  # ====================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true

# ====================
# OPENAPI/SWAGGER CONFIG
# ====================
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /api-docs
    config-url: /api-docs/swagger-config
    disable-swagger-default-url: true
  paths-to-match: /**
  use-fqn: true

# ====================
# EUREKA CONFIGURATION
# ====================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    statusPageUrl: http://localhost:${server.port}/actuator/info
    healthCheckUrl: http://localhost:${server.port}/actuator/health
    homePageUrl: http://localhost:${server.port}/swagger-ui.html
    homePageUrlPath: ${server.servlet.context-path}/equipes/all

  # ====================
  # SECURITY DISABLE (CRUCIAL FIX)
  # ====================

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# ====================
# ACTUATOR CONFIGURATION
# ====================
management:
  endpoints:
    web:
      exposure:
        include: refresh
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# ====================
# INFO ENDPOINT CONFIG
# ====================
info:
  app:
    name: match Service
    description: Service de gestion des joueurs
    version: 1.0.0
    java:
      version: ${java.version}
    spring-cloud:
      version: ${spring-cloud.version}
    spring-boot:
      version: ${spring-boot.version}