spring:
  application:
    name: football-service

  datasource:
    username: user-service
    password: ""
    url: jdbc:h2:file:/opt/app/database/footballdb;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  ssl:
    ignore-ssl-errors: true  # Non-standard property, verify usage

server:
  port: 8060
  servlet:
    context-path: ""  # Empty context path, equivalent to "/"

welcome:
  message: Welcome to user

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: false
  instance:
    prefer-ip-address: true
    hostname: eureka
    instance-id: ${spring.application.name}:${server.port}
    status-page-url: http://localhost:8086/users/all
    health-check-url: http://localhost:8086/actuator/health
    home-page-url: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/users/all

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true



face:
  recognition:
    api:
      url: http://localhost:5000

openweathermap:
  api:
    key: 04b1c1cdd80f54406dae914815a7cf57